////
 * Copyright (C) Eclipse Foundation, Inc. and others. 
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
////

[[efspo-faq]]
= Frequently Asked Questions

[qanda]
Is a specification project is a subtype of a Eclipse project, governed by the EDP? ::

In a mathematical sense, yes. A specification project as defined by the EFSP is a specialization or subtype of an Eclipse open source project as defined by the EDP.

Does a specification need to list patents? ::

No. In fact, a specification _must not_ specifically list patents.

How do patent grants work? ::

We cannot provide legal advice. Connect with your lawyer for more information.

Can a working group's steering committee take on the responsibilities of the specification committee? ::

Yes. A working group's charter can assign the responsibilities of the specification committee to any working group committee.

The ability of a member participant (i.e., a participant representing a company) to appoint a _participant representative_ committer isn't very meritocratic; is meritocracy irrelevant? ::

Meritocracy is very relevant. However, the rules of engagement with specification projects is different in consideration of factors like patent grants and antitrust. In the case of specifications, vendor-neutrality trumps meritocracy: a specification process must be accessible to all *companies* who wish to participate.

Can a member participant (i.e., a participant representing a company) appoint as many _participant representative_ committers as they'd like? ::

No. A member participant (i.e., a company that is a participant in the working group) can appoint a single participant representative committer on a specification project, and only if they do not already have a committer representing their interests on that project. Additional committers representing the interests of a member participant may demonstrate merit through contribution and be elected to the project using the standard mechanism for {handbookCommitterElectionsUrl}[electing committers].

Is a participant representative a special kind of committer? ::

A participant representative is indistinguishable from any other committer once appointed.

Do participant representatives have any special powers or privileges? ::

No. Participant representatives have exactly the same privileges and responsibilities as any other committer.

Will a participant representative be retired from a specification project when they change employers? ::

No. A participant representative is indistinguishable from any other committer and so retains their committer status even after changing employers. After changing employers, a committer may require new committer agreements, but once those are in place, the committer retains all privileges. In the event that a committer changing employers leaves a member participant unrepresented, that member participant may appoint a new participant representative.

How does the role of the Specification Committee differ from the role of the PMC? ::

The Project Management Committee (PMC) manages the technical governance process, and provides oversight. It ensures that the open source rules of engagement are observed and the Eclipse Development Process (EDP) as a whole is followed. It participates in the Intellectual Property Due Diligence Process to ensure that requests for review are technically sound (for example, to ensure that the use of third-party content makes technical sense). The PMC provides best practices. It tends to work more at the development and technical level.
+
The Specification Committee is responsible for ensuring that the rules and processes outlined by the EFSP are implemented by Specification Projects, that the integrity of the Scope is maintained (e.g. that release plans define changes that are in-scope), that community has been properly consulted, implementation is technical feasible, and that the Specification otherwise remains consistent with the goals of the Working Group.
+
The PMC is in the Project Leadership Chain; the Specification Committee is not. Approvals from both parties are required for Progress and Release Reviews.


If a Specification Project is archived, do the Final Specifications that it previously produced remain valid? ::

Yes. All previously created Final Specifications remain valid. 

What does it mean for a Specification Project to be “under the supervision” of a Specification Committee? ::

A Specification Project effectively belongs to one Working Group. By aligning itself with a particular Working Group, a Specification Project agrees to take direction from the corresponding Specification Committee. 

How does the Specification Committee manage the overall roadmap for the Specification Projects under their supervision? ::

How a Specification Committee manages a roadmap varies based on the nature of the parties involved. The Specification Committee may choose to defer this responsibility to one of the Specification Projects (e.g. a _Platform_ Specification Project). The roadmap itself may take the form of a set of published guidelines or best practices, the implementation of a simultaneous release, or required themes and other elements in Release Plans. Ultimately, the Specification Committee should work with the PMC and the Project Teams to build consensus rather than impose rules.

[[efsp-faq-plan-1]]By what criteria does the specification committee assess a plan? What constitutes an acceptable plan? ::

When reviewing a plan, the question that specification committee members need to answer is whether or not they, would vote to approve the eventual completion of that plan when the project returns to the committee for a release review.
+
Specification committee members have to decide whether or not, for example, themes and plan items described in a plan are something they would actually want to see in an implementation of the specification.
+
A specification committees may opt to make specific requirements for plans (including delivery format). That notwithstanding, how specification committee members vote is left to the discretion of the individual committee members. 

What happens if a Review fails? ::

The party that fails (i.e. denies approval) the review is expected to provide feedback in the event of failure. The Specification Team will engage with the party to determine the correct course of action. That course of action may be to re-engage in the Review at a later date or take some other corrective action. In any case, the Reviews required by the process must be completed successfully to proceed to the next step.

What do I do if I feel that my Review was failed unfairly? ::

Follow the Grievance Handling process defined in the EDP.

How is the association of the artifacts of a particular Specification Version represented? ::

The Specification Committee should provide best practices to Specification Projects, for example, a standard metadata format.

What is the difference between a Specification Version and a Final Specification? ::

A Specification Version is produced by a release cycle, then becomes a Final Specification when it is Ratified and distributed under the Eclipse Foundation Specification License (EFSL).
+
The intellectual property rights required to build a Compatible Implementation flow from the Final Specification. That is, in order to be considered a Compatible Implementation and benefit from the intellectual property protections, an implementation must be based on a final specification. No claims regarding compatibility may be made for an implementation based on a milestone build or unratified Specification Version.

What types of changes are not appropriate for a Service Release? ::

Changes to method signatures or additions of new methods or behavior (for example) are generally not considered appropriate in a Service Release. A Specification Team should consult with their PMC and Specification Committee to determine precisely what sort of review is required for a particular change.

Are Specification Projects required to implement the Eclipse IP Policy and engage in the Eclipse IP Due Diligence Process? ::

Yes.
